config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :sessions
  resources :films
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/film.rb
class Film < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:email, :phone)
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy ]

  # GET /films or /films.json
  def index
    @films = Film.all
  end

  # GET /films/1 or /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films or /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to film_url(@film), notice: "Film was successfully created." }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to film_url(@film), notice: "Film was successfully updated." }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url, notice: "Film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:name, :janr, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_session, only: %i[ show edit update destroy ]

  # GET /sessions or /sessions.json
  def index
    @sessions = Session.all
  end

  # GET /sessions/1 or /sessions/1.json
  def show
  end

  # GET /sessions/new
  def new
    @session = Session.new
  end

  # GET /sessions/1/edit
  def edit
  end

  # POST /sessions or /sessions.json
  def create
    @session = Session.new(session_params)

    respond_to do |format|
      if @session.save
        format.html { redirect_to session_url(@session), notice: "Session was successfully created." }
        format.json { render :show, status: :created, location: @session }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sessions/1 or /sessions/1.json
  def update
    respond_to do |format|
      if @session.update(session_params)
        format.html { redirect_to session_url(@session), notice: "Session was successfully updated." }
        format.json { render :show, status: :ok, location: @session }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sessions/1 or /sessions/1.json
  def destroy
    @session.destroy

    respond_to do |format|
      format.html { redirect_to sessions_url, notice: "Session was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session
      @session = Session.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def session_params
      params.require(:session).permit(:zal, :datas, :film)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p>
    <strong>Email:</strong>
    <%= customer.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= customer.phone %>
  </p>

</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Customers</h1>

<div id="customers">
  <% @customers.each do |customer| %>
    <%= render customer %>
    <p>
      <%= link_to "Show this customer", customer %>
    </p>
  <% end %>
</div>

<%= link_to "New customer", new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer) %> |
  <%= link_to "Back to customers", customers_path %>

  <%= button_to "Destroy this customer", @customer, method: :delete %>
</div>

app/views/films/_film.html.erb
<div id="<%= dom_id film %>">
  <p>
    <strong>Name:</strong>
    <%= film.name %>
  </p>

  <p>
    <strong>Janr:</strong>
    <%= film.janr %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= film.date %>
  </p>

</div>

app/views/films/_form.html.erb
<%= form_with(model: film) do |form| %>
  <% if film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
        <% film.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :janr, style: "display: block" %>
    <%= form.text_field :janr %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.text_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Show this film", @film %> |
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Films</h1>

<div id="films">
  <% @films.each do |film| %>
    <%= render film %>
    <p>
      <%= link_to "Show this film", film %>
    </p>
  <% end %>
</div>

<%= link_to "New film", new_film_path %>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @film %>

<div>
  <%= link_to "Edit this film", edit_film_path(@film) %> |
  <%= link_to "Back to films", films_path %>

  <%= button_to "Destroy this film", @film, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kinoteatr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>